/*
Copyright 2020 waveywaves

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/waveywaves/cloudevents-controller/pkg/apis/samples/v1alpha1"
	scheme "github.com/waveywaves/cloudevents-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CloudeventSinksGetter has a method to return a CloudeventSinkInterface.
// A group's client should implement this interface.
type CloudeventSinksGetter interface {
	CloudeventSinks(namespace string) CloudeventSinkInterface
}

// CloudeventSinkInterface has methods to work with CloudeventSink resources.
type CloudeventSinkInterface interface {
	Create(ctx context.Context, cloudeventSink *v1alpha1.CloudeventSink, opts v1.CreateOptions) (*v1alpha1.CloudeventSink, error)
	Update(ctx context.Context, cloudeventSink *v1alpha1.CloudeventSink, opts v1.UpdateOptions) (*v1alpha1.CloudeventSink, error)
	UpdateStatus(ctx context.Context, cloudeventSink *v1alpha1.CloudeventSink, opts v1.UpdateOptions) (*v1alpha1.CloudeventSink, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.CloudeventSink, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.CloudeventSinkList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CloudeventSink, err error)
	CloudeventSinkExpansion
}

// cloudeventSinks implements CloudeventSinkInterface
type cloudeventSinks struct {
	client rest.Interface
	ns     string
}

// newCloudeventSinks returns a CloudeventSinks
func newCloudeventSinks(c *CloudeventsV1alpha1Client, namespace string) *cloudeventSinks {
	return &cloudeventSinks{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cloudeventSink, and returns the corresponding cloudeventSink object, and an error if there is any.
func (c *cloudeventSinks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CloudeventSink, err error) {
	result = &v1alpha1.CloudeventSink{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cloudeventsinks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CloudeventSinks that match those selectors.
func (c *cloudeventSinks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CloudeventSinkList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CloudeventSinkList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cloudeventsinks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cloudeventSinks.
func (c *cloudeventSinks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cloudeventsinks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a cloudeventSink and creates it.  Returns the server's representation of the cloudeventSink, and an error, if there is any.
func (c *cloudeventSinks) Create(ctx context.Context, cloudeventSink *v1alpha1.CloudeventSink, opts v1.CreateOptions) (result *v1alpha1.CloudeventSink, err error) {
	result = &v1alpha1.CloudeventSink{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cloudeventsinks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cloudeventSink).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a cloudeventSink and updates it. Returns the server's representation of the cloudeventSink, and an error, if there is any.
func (c *cloudeventSinks) Update(ctx context.Context, cloudeventSink *v1alpha1.CloudeventSink, opts v1.UpdateOptions) (result *v1alpha1.CloudeventSink, err error) {
	result = &v1alpha1.CloudeventSink{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cloudeventsinks").
		Name(cloudeventSink.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cloudeventSink).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *cloudeventSinks) UpdateStatus(ctx context.Context, cloudeventSink *v1alpha1.CloudeventSink, opts v1.UpdateOptions) (result *v1alpha1.CloudeventSink, err error) {
	result = &v1alpha1.CloudeventSink{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cloudeventsinks").
		Name(cloudeventSink.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cloudeventSink).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the cloudeventSink and deletes it. Returns an error if one occurs.
func (c *cloudeventSinks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cloudeventsinks").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cloudeventSinks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cloudeventsinks").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched cloudeventSink.
func (c *cloudeventSinks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CloudeventSink, err error) {
	result = &v1alpha1.CloudeventSink{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cloudeventsinks").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
