# Copyright 2018 waveywaves
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: defaulting.webhook.cloudevents.waveywaves.dev
  labels:
    cloudevents.waveywaves.dev/release: devel
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook
      namespace: cloudevents-controller
  failurePolicy: Fail
  sideEffects: None
  name: defaulting.webhook.cloudevents.waveywaves.dev
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.cloudevents.waveywaves.dev
  labels:
    cloudevents.waveywaves.dev/release: devel
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook
      namespace: cloudevents-controller
  failurePolicy: Fail
  sideEffects: None
  name: validation.webhook.cloudevents.waveywaves.dev
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: config.webhook.cloudevents.waveywaves.dev
  labels:
    serving.knative.dev/release: devel
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook
      namespace: cloudevents-controller
  failurePolicy: Fail
  sideEffects: None
  name: config.webhook.cloudevents.waveywaves.dev
  namespaceSelector:
    matchExpressions:
    - key: cloudevents.waveywaves.dev/release
      operator: Exists
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  namespace: cloudevents-controller
  labels:
    cloudevents.waveywaves.dev/release: devel
# The data is populated at install time.
