/*
Copyright 2020 waveywaves

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/waveywaves/cloudevents-controller/pkg/apis/samples/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCloudeventSinks implements CloudeventSinkInterface
type FakeCloudeventSinks struct {
	Fake *FakeCloudeventsV1alpha1
	ns   string
}

var cloudeventsinksResource = schema.GroupVersionResource{Group: "cloudevents.waveywaves.dev", Version: "v1alpha1", Resource: "cloudeventsinks"}

var cloudeventsinksKind = schema.GroupVersionKind{Group: "cloudevents.waveywaves.dev", Version: "v1alpha1", Kind: "CloudeventSink"}

// Get takes name of the cloudeventSink, and returns the corresponding cloudeventSink object, and an error if there is any.
func (c *FakeCloudeventSinks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CloudeventSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cloudeventsinksResource, c.ns, name), &v1alpha1.CloudeventSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CloudeventSink), err
}

// List takes label and field selectors, and returns the list of CloudeventSinks that match those selectors.
func (c *FakeCloudeventSinks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CloudeventSinkList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cloudeventsinksResource, cloudeventsinksKind, c.ns, opts), &v1alpha1.CloudeventSinkList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CloudeventSinkList{ListMeta: obj.(*v1alpha1.CloudeventSinkList).ListMeta}
	for _, item := range obj.(*v1alpha1.CloudeventSinkList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cloudeventSinks.
func (c *FakeCloudeventSinks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cloudeventsinksResource, c.ns, opts))

}

// Create takes the representation of a cloudeventSink and creates it.  Returns the server's representation of the cloudeventSink, and an error, if there is any.
func (c *FakeCloudeventSinks) Create(ctx context.Context, cloudeventSink *v1alpha1.CloudeventSink, opts v1.CreateOptions) (result *v1alpha1.CloudeventSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cloudeventsinksResource, c.ns, cloudeventSink), &v1alpha1.CloudeventSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CloudeventSink), err
}

// Update takes the representation of a cloudeventSink and updates it. Returns the server's representation of the cloudeventSink, and an error, if there is any.
func (c *FakeCloudeventSinks) Update(ctx context.Context, cloudeventSink *v1alpha1.CloudeventSink, opts v1.UpdateOptions) (result *v1alpha1.CloudeventSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cloudeventsinksResource, c.ns, cloudeventSink), &v1alpha1.CloudeventSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CloudeventSink), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCloudeventSinks) UpdateStatus(ctx context.Context, cloudeventSink *v1alpha1.CloudeventSink, opts v1.UpdateOptions) (*v1alpha1.CloudeventSink, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cloudeventsinksResource, "status", c.ns, cloudeventSink), &v1alpha1.CloudeventSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CloudeventSink), err
}

// Delete takes name of the cloudeventSink and deletes it. Returns an error if one occurs.
func (c *FakeCloudeventSinks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cloudeventsinksResource, c.ns, name), &v1alpha1.CloudeventSink{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCloudeventSinks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cloudeventsinksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CloudeventSinkList{})
	return err
}

// Patch applies the patch and returns the patched cloudeventSink.
func (c *FakeCloudeventSinks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CloudeventSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cloudeventsinksResource, c.ns, name, pt, data, subresources...), &v1alpha1.CloudeventSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CloudeventSink), err
}
